// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/render-oss/render-mcp-server/pkg/client"
)

type FakeDeployRepoClient struct {
	CreateDeployWithResponseStub        func(context.Context, client.ServiceIdParam, client.CreateDeployJSONRequestBody, ...client.RequestEditorFn) (*client.CreateDeployResponse, error)
	createDeployWithResponseMutex       sync.RWMutex
	createDeployWithResponseArgsForCall []struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 client.CreateDeployJSONRequestBody
		arg4 []client.RequestEditorFn
	}
	createDeployWithResponseReturns struct {
		result1 *client.CreateDeployResponse
		result2 error
	}
	createDeployWithResponseReturnsOnCall map[int]struct {
		result1 *client.CreateDeployResponse
		result2 error
	}
	ListDeploysWithResponseStub        func(context.Context, client.ServiceIdParam, *client.ListDeploysParams, ...client.RequestEditorFn) (*client.ListDeploysResponse, error)
	listDeploysWithResponseMutex       sync.RWMutex
	listDeploysWithResponseArgsForCall []struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 *client.ListDeploysParams
		arg4 []client.RequestEditorFn
	}
	listDeploysWithResponseReturns struct {
		result1 *client.ListDeploysResponse
		result2 error
	}
	listDeploysWithResponseReturnsOnCall map[int]struct {
		result1 *client.ListDeploysResponse
		result2 error
	}
	RetrieveDeployWithResponseStub        func(context.Context, client.ServiceIdParam, client.DeployIdParam, ...client.RequestEditorFn) (*client.RetrieveDeployResponse, error)
	retrieveDeployWithResponseMutex       sync.RWMutex
	retrieveDeployWithResponseArgsForCall []struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 client.DeployIdParam
		arg4 []client.RequestEditorFn
	}
	retrieveDeployWithResponseReturns struct {
		result1 *client.RetrieveDeployResponse
		result2 error
	}
	retrieveDeployWithResponseReturnsOnCall map[int]struct {
		result1 *client.RetrieveDeployResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDeployRepoClient) CreateDeployWithResponse(arg1 context.Context, arg2 client.ServiceIdParam, arg3 client.CreateDeployJSONRequestBody, arg4 ...client.RequestEditorFn) (*client.CreateDeployResponse, error) {
	fake.createDeployWithResponseMutex.Lock()
	ret, specificReturn := fake.createDeployWithResponseReturnsOnCall[len(fake.createDeployWithResponseArgsForCall)]
	fake.createDeployWithResponseArgsForCall = append(fake.createDeployWithResponseArgsForCall, struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 client.CreateDeployJSONRequestBody
		arg4 []client.RequestEditorFn
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateDeployWithResponseStub
	fakeReturns := fake.createDeployWithResponseReturns
	fake.recordInvocation("CreateDeployWithResponse", []interface{}{arg1, arg2, arg3, arg4})
	fake.createDeployWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDeployRepoClient) CreateDeployWithResponseCallCount() int {
	fake.createDeployWithResponseMutex.RLock()
	defer fake.createDeployWithResponseMutex.RUnlock()
	return len(fake.createDeployWithResponseArgsForCall)
}

func (fake *FakeDeployRepoClient) CreateDeployWithResponseCalls(stub func(context.Context, client.ServiceIdParam, client.CreateDeployJSONRequestBody, ...client.RequestEditorFn) (*client.CreateDeployResponse, error)) {
	fake.createDeployWithResponseMutex.Lock()
	defer fake.createDeployWithResponseMutex.Unlock()
	fake.CreateDeployWithResponseStub = stub
}

func (fake *FakeDeployRepoClient) CreateDeployWithResponseArgsForCall(i int) (context.Context, client.ServiceIdParam, client.CreateDeployJSONRequestBody, []client.RequestEditorFn) {
	fake.createDeployWithResponseMutex.RLock()
	defer fake.createDeployWithResponseMutex.RUnlock()
	argsForCall := fake.createDeployWithResponseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeDeployRepoClient) CreateDeployWithResponseReturns(result1 *client.CreateDeployResponse, result2 error) {
	fake.createDeployWithResponseMutex.Lock()
	defer fake.createDeployWithResponseMutex.Unlock()
	fake.CreateDeployWithResponseStub = nil
	fake.createDeployWithResponseReturns = struct {
		result1 *client.CreateDeployResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDeployRepoClient) CreateDeployWithResponseReturnsOnCall(i int, result1 *client.CreateDeployResponse, result2 error) {
	fake.createDeployWithResponseMutex.Lock()
	defer fake.createDeployWithResponseMutex.Unlock()
	fake.CreateDeployWithResponseStub = nil
	if fake.createDeployWithResponseReturnsOnCall == nil {
		fake.createDeployWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.CreateDeployResponse
			result2 error
		})
	}
	fake.createDeployWithResponseReturnsOnCall[i] = struct {
		result1 *client.CreateDeployResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDeployRepoClient) ListDeploysWithResponse(arg1 context.Context, arg2 client.ServiceIdParam, arg3 *client.ListDeploysParams, arg4 ...client.RequestEditorFn) (*client.ListDeploysResponse, error) {
	fake.listDeploysWithResponseMutex.Lock()
	ret, specificReturn := fake.listDeploysWithResponseReturnsOnCall[len(fake.listDeploysWithResponseArgsForCall)]
	fake.listDeploysWithResponseArgsForCall = append(fake.listDeploysWithResponseArgsForCall, struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 *client.ListDeploysParams
		arg4 []client.RequestEditorFn
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListDeploysWithResponseStub
	fakeReturns := fake.listDeploysWithResponseReturns
	fake.recordInvocation("ListDeploysWithResponse", []interface{}{arg1, arg2, arg3, arg4})
	fake.listDeploysWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDeployRepoClient) ListDeploysWithResponseCallCount() int {
	fake.listDeploysWithResponseMutex.RLock()
	defer fake.listDeploysWithResponseMutex.RUnlock()
	return len(fake.listDeploysWithResponseArgsForCall)
}

func (fake *FakeDeployRepoClient) ListDeploysWithResponseCalls(stub func(context.Context, client.ServiceIdParam, *client.ListDeploysParams, ...client.RequestEditorFn) (*client.ListDeploysResponse, error)) {
	fake.listDeploysWithResponseMutex.Lock()
	defer fake.listDeploysWithResponseMutex.Unlock()
	fake.ListDeploysWithResponseStub = stub
}

func (fake *FakeDeployRepoClient) ListDeploysWithResponseArgsForCall(i int) (context.Context, client.ServiceIdParam, *client.ListDeploysParams, []client.RequestEditorFn) {
	fake.listDeploysWithResponseMutex.RLock()
	defer fake.listDeploysWithResponseMutex.RUnlock()
	argsForCall := fake.listDeploysWithResponseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeDeployRepoClient) ListDeploysWithResponseReturns(result1 *client.ListDeploysResponse, result2 error) {
	fake.listDeploysWithResponseMutex.Lock()
	defer fake.listDeploysWithResponseMutex.Unlock()
	fake.ListDeploysWithResponseStub = nil
	fake.listDeploysWithResponseReturns = struct {
		result1 *client.ListDeploysResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDeployRepoClient) ListDeploysWithResponseReturnsOnCall(i int, result1 *client.ListDeploysResponse, result2 error) {
	fake.listDeploysWithResponseMutex.Lock()
	defer fake.listDeploysWithResponseMutex.Unlock()
	fake.ListDeploysWithResponseStub = nil
	if fake.listDeploysWithResponseReturnsOnCall == nil {
		fake.listDeploysWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ListDeploysResponse
			result2 error
		})
	}
	fake.listDeploysWithResponseReturnsOnCall[i] = struct {
		result1 *client.ListDeploysResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDeployRepoClient) RetrieveDeployWithResponse(arg1 context.Context, arg2 client.ServiceIdParam, arg3 client.DeployIdParam, arg4 ...client.RequestEditorFn) (*client.RetrieveDeployResponse, error) {
	fake.retrieveDeployWithResponseMutex.Lock()
	ret, specificReturn := fake.retrieveDeployWithResponseReturnsOnCall[len(fake.retrieveDeployWithResponseArgsForCall)]
	fake.retrieveDeployWithResponseArgsForCall = append(fake.retrieveDeployWithResponseArgsForCall, struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 client.DeployIdParam
		arg4 []client.RequestEditorFn
	}{arg1, arg2, arg3, arg4})
	stub := fake.RetrieveDeployWithResponseStub
	fakeReturns := fake.retrieveDeployWithResponseReturns
	fake.recordInvocation("RetrieveDeployWithResponse", []interface{}{arg1, arg2, arg3, arg4})
	fake.retrieveDeployWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDeployRepoClient) RetrieveDeployWithResponseCallCount() int {
	fake.retrieveDeployWithResponseMutex.RLock()
	defer fake.retrieveDeployWithResponseMutex.RUnlock()
	return len(fake.retrieveDeployWithResponseArgsForCall)
}

func (fake *FakeDeployRepoClient) RetrieveDeployWithResponseCalls(stub func(context.Context, client.ServiceIdParam, client.DeployIdParam, ...client.RequestEditorFn) (*client.RetrieveDeployResponse, error)) {
	fake.retrieveDeployWithResponseMutex.Lock()
	defer fake.retrieveDeployWithResponseMutex.Unlock()
	fake.RetrieveDeployWithResponseStub = stub
}

func (fake *FakeDeployRepoClient) RetrieveDeployWithResponseArgsForCall(i int) (context.Context, client.ServiceIdParam, client.DeployIdParam, []client.RequestEditorFn) {
	fake.retrieveDeployWithResponseMutex.RLock()
	defer fake.retrieveDeployWithResponseMutex.RUnlock()
	argsForCall := fake.retrieveDeployWithResponseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeDeployRepoClient) RetrieveDeployWithResponseReturns(result1 *client.RetrieveDeployResponse, result2 error) {
	fake.retrieveDeployWithResponseMutex.Lock()
	defer fake.retrieveDeployWithResponseMutex.Unlock()
	fake.RetrieveDeployWithResponseStub = nil
	fake.retrieveDeployWithResponseReturns = struct {
		result1 *client.RetrieveDeployResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDeployRepoClient) RetrieveDeployWithResponseReturnsOnCall(i int, result1 *client.RetrieveDeployResponse, result2 error) {
	fake.retrieveDeployWithResponseMutex.Lock()
	defer fake.retrieveDeployWithResponseMutex.Unlock()
	fake.RetrieveDeployWithResponseStub = nil
	if fake.retrieveDeployWithResponseReturnsOnCall == nil {
		fake.retrieveDeployWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.RetrieveDeployResponse
			result2 error
		})
	}
	fake.retrieveDeployWithResponseReturnsOnCall[i] = struct {
		result1 *client.RetrieveDeployResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDeployRepoClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createDeployWithResponseMutex.RLock()
	defer fake.createDeployWithResponseMutex.RUnlock()
	fake.listDeploysWithResponseMutex.RLock()
	defer fake.listDeploysWithResponseMutex.RUnlock()
	fake.retrieveDeployWithResponseMutex.RLock()
	defer fake.retrieveDeployWithResponseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDeployRepoClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
