// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/render-oss/render-mcp-server/pkg/client"
)

type FakeEventRepoClient struct {
	ListEventsWithResponseStub        func(context.Context, client.ServiceIdParam, *client.ListEventsParams, ...client.RequestEditorFn) (*client.ListEventsResponse, error)
	listEventsWithResponseMutex       sync.RWMutex
	listEventsWithResponseArgsForCall []struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 *client.ListEventsParams
		arg4 []client.RequestEditorFn
	}
	listEventsWithResponseReturns struct {
		result1 *client.ListEventsResponse
		result2 error
	}
	listEventsWithResponseReturnsOnCall map[int]struct {
		result1 *client.ListEventsResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEventRepoClient) ListEventsWithResponse(arg1 context.Context, arg2 client.ServiceIdParam, arg3 *client.ListEventsParams, arg4 ...client.RequestEditorFn) (*client.ListEventsResponse, error) {
	var arg4Copy []client.RequestEditorFn
	if arg4 != nil {
		arg4Copy = make([]client.RequestEditorFn, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.listEventsWithResponseMutex.Lock()
	ret, specificReturn := fake.listEventsWithResponseReturnsOnCall[len(fake.listEventsWithResponseArgsForCall)]
	fake.listEventsWithResponseArgsForCall = append(fake.listEventsWithResponseArgsForCall, struct {
		arg1 context.Context
		arg2 client.ServiceIdParam
		arg3 *client.ListEventsParams
		arg4 []client.RequestEditorFn
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.ListEventsWithResponseStub
	fakeReturns := fake.listEventsWithResponseReturns
	fake.recordInvocation("ListEventsWithResponse", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.listEventsWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEventRepoClient) ListEventsWithResponseCallCount() int {
	fake.listEventsWithResponseMutex.RLock()
	defer fake.listEventsWithResponseMutex.RUnlock()
	return len(fake.listEventsWithResponseArgsForCall)
}

func (fake *FakeEventRepoClient) ListEventsWithResponseCalls(stub func(context.Context, client.ServiceIdParam, *client.ListEventsParams, ...client.RequestEditorFn) (*client.ListEventsResponse, error)) {
	fake.listEventsWithResponseMutex.Lock()
	defer fake.listEventsWithResponseMutex.Unlock()
	fake.ListEventsWithResponseStub = stub
}

func (fake *FakeEventRepoClient) ListEventsWithResponseArgsForCall(i int) (context.Context, client.ServiceIdParam, *client.ListEventsParams, []client.RequestEditorFn) {
	fake.listEventsWithResponseMutex.RLock()
	defer fake.listEventsWithResponseMutex.RUnlock()
	argsForCall := fake.listEventsWithResponseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeEventRepoClient) ListEventsWithResponseReturns(result1 *client.ListEventsResponse, result2 error) {
	fake.listEventsWithResponseMutex.Lock()
	defer fake.listEventsWithResponseMutex.Unlock()
	fake.ListEventsWithResponseStub = nil
	fake.listEventsWithResponseReturns = struct {
		result1 *client.ListEventsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeEventRepoClient) ListEventsWithResponseReturnsOnCall(i int, result1 *client.ListEventsResponse, result2 error) {
	fake.listEventsWithResponseMutex.Lock()
	defer fake.listEventsWithResponseMutex.Unlock()
	fake.ListEventsWithResponseStub = nil
	if fake.listEventsWithResponseReturnsOnCall == nil {
		fake.listEventsWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ListEventsResponse
			result2 error
		})
	}
	fake.listEventsWithResponseReturnsOnCall[i] = struct {
		result1 *client.ListEventsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeEventRepoClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEventRepoClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
